name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Build and Test 3.3
        run: sbt -v test
      - name: Build and Test 3.4
        run: sbt -v ++3.4 test
      - name: Build and Test 3.5
        run: sbt -v ++3.5.0-RC1 test